version = 0.1

[default.deploy.parameters]
stack_name = "TechChallenge4-Processor"
resolve_s3 = true
s3_prefix = "TechChallenge4-Processor"
capabilities = "CAPABILITY_IAM"
# Removida a linha 'image_repositories' para evitar conflito com --resolve-image-repos do CI/CD
parameter_overrides = "DynamoDbTableName=\"Feedbacks\" AdminEmail=\"jeferson.herculano@outlook.com\" SourceEmail=\"jh93.dev@gmail.com\""

[default.global.parameters]
# Garanta que esta região é a mesma configurada no seu GitHub Secrets (AWS_REGION)
region = "sa-east-1"