version = 0.1

[default.deploy.parameters]
stack_name = "TechChallenge4-Processor"
resolve_s3 = true
s3_prefix = "TechChallenge4-Processor"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "DynamoDbTableName=\"Feedbacks\" AdminEmail=\"gustavo.jog+admin@hotmail.com\" SourceEmail=\"gustavo.jog+no-reply@hotmail.com\""
# AQUI ESTAVA O ERRO: NÃ£o deixe 'image_repositories' nem 'resolve_image_repos' aqui.
# Deixe que o comando no GitHub Actions cuide disso.

[default.global.parameters]
region = "us-east-1"
